import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

export default [
  { ignores: ['dist', '.cache', 'node_modules', 'attached_assets'] },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'no-var': 'off',
      'prefer-const': 'off',
      'no-unused-vars': 'off',
      'no-undef': 'off',
      'object-shorthand': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-template': 'off',
      'no-console': 'off',
      'no-debugger': 'off',
      'no-empty': 'off',
      'no-constant-condition': 'off',
      'no-unreachable': 'off',
      'no-useless-escape': 'off',
      'no-prototype-builtins': 'off',
      'no-fallthrough': 'off',
      'no-case-declarations': 'off',
      'no-redeclare': 'off',
      'no-inner-declarations': 'off',
      'no-func-assign': 'off',
      'no-extra-boolean-cast': 'off',
      'no-irregular-whitespace': 'off',
      'no-mixed-spaces-and-tabs': 'off',
      'no-sparse-arrays': 'off',
      'valid-typeof': 'off',
      'no-unsafe-negation': 'off',
      'no-global-assign': 'off',
      'no-self-assign': 'off',
      'no-unused-labels': 'off',
      'no-delete-var': 'off',
      'no-label-var': 'off',
      'no-shadow-restricted-names': 'off',
      'no-undef-init': 'off',
      'use-isnan': 'off',
      'no-compare-neg-zero': 'off',
      'require-yield': 'off',
      'getter-return': 'off',
      'no-setter-return': 'off',
      'no-async-promise-executor': 'off',
      'no-await-in-loop': 'off',
      'no-misleading-character-class': 'off',
      'no-template-curly-in-string': 'off',
      'require-atomic-updates': 'off',
    },
  },
];